# Generated by Django 3.1.4 on 2021-01-03 17:26

from django.db import migrations, models
import page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_file', models.FileField(upload_to=page.models.get_upload_path)),
            ],
        ),
    ]
